version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: ipauth-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: ipauth
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./backend/src/migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d ipauth"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ipauth-api
    environment:
      DATABASE_URL: postgres://user:pass@db:5432/ipauth
      PORT: 3000
      NODE_ENV: production
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: ipauth-frontend
    environment:
      VITE_API_BASE: http://localhost:3000/v1
    ports:
      - "5173:80"
    depends_on:
      - api
    restart: unless-stopped

volumes:
  pgdata:
